name: playing around

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  echo:
    name: echo
    runs-on: self-hosted
    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: echoing "oi"
        run: echo "oi"

  list-my-files:
    runs-on: self-hosted
    steps:
      - name: List files in the repository
        run: |
          ls ${{ github.workspace }}
